AUGMENTATION_TRAIN: 0
BATCH_SIZE: 1
BETA1: 0.0
BETA2: 0.9
CONTENT_LOSS_WEIGHT: 0.1
D2G_LR: 0.1
EVAL_INTERVAL: 0
GAN_LOSS: lsgan
GAN_POOL_SIZE: 0
GPU: [1]
INPAINT_ADV_LOSS_WEIGHT: 1
INPUT_SIZE: 512
L1_LOSS_WEIGHT: 10
LANDMARK_POINTS: 68
LOG_INTERVAL: 100
LR: 0.00005
MASK: 6
MAX_ITERS: 1300000
MODE: 2
MODEL: 3
SAMPLE_INTERVAL: 100
SAMPLE_SIZE: 2
SAVE_INTERVAL: 100
SEED: 10
STYLE_LOSS_WEIGHT: 250

TEST_INPAINT_IMAGE_FLIST: datasets/celebahqr/test/images.flist
TEST_INPAINT_LANDMARK_FLIST: datasets/celebahqr/test/landmarks.flist
TEST_LANDMARK_IMAGE_FLIST: null
TEST_LANDMARK_LANDMARK_FLIST: null
TEST_MASK_FLIST: datasets/celebahqr/test/masks.flist


TRAIN_INPAINT_IMAGE_FLIST: datasets/celebahqr/train/images.flist
TRAIN_INPAINT_LANDMARK_FLIST: datasets/celebahqr/train/landmarks.flist
TRAIN_LANDMARK_IMAGE_FLIST: null
TRAIN_LANDMARK_LANDMARK_FLIST: null
TRAIN_MASK_FLIST: datasets/celebahqr/train/masks.flist
TV_LOSS_WEIGHT: 0.1
VAL_INPAINT_IMAGE_FLIST: datasets/celebahqr/val/images.flist
VAL_INPAINT_LANDMARK_FLIST: datasets/celebahqr/val/landmarks.flist
VAL_MASK_FLIST: datasets/celebahqr/val/masks.flist

DATA_ROOT: /home/cb/celeba-1024-lafin
INPAINTOR: stylegan_base_faceae
LOCAL: False
ATT_LOSS_WEIGHT: 100
LM_LOSS_WEIGHT: 10
ID_LOSS_WEIGHT: 0.5
LATENT: 1024
FMAP_MAX: 512
DISTRIBUTED: True