AUGMENTATION_TRAIN: 0
BATCH_SIZE: 4
BETA1: 0.0
BETA2: 0.9
CONTENT_LOSS_WEIGHT: 0.1
D2G_LR: 0.1
EVAL_INTERVAL: 0
GAN_LOSS: lsgan
GAN_POOL_SIZE: 0
GPU: [4]
INPAINT_ADV_LOSS_WEIGHT: 0.01
INPUT_SIZE: 256
L1_LOSS_WEIGHT: 1
LANDMARK_POINTS: 68
LOG_INTERVAL: 100
LR: 0.001
MASK: 6
MAX_ITERS: 1300000
MODE: 2
MODEL: 3
SAMPLE_INTERVAL: 200
SAMPLE_SIZE: 2
SAVE_INTERVAL: 1000
SEED: 10
STYLE_LOSS_WEIGHT: 250
TEST_INPAINT_IMAGE_FLIST: datasets/celeba-1024-lafin/test/images.flist
TEST_INPAINT_LANDMARK_FLIST: datasets/celeba-1024-lafin/test/landmarks.flist
TEST_LANDMARK_IMAGE_FLIST: null
TEST_LANDMARK_LANDMARK_FLIST: null
TEST_MASK_FLIST: datasets/celeba-1024-lafin/test/masks.flist
TRAIN_INPAINT_IMAGE_FLIST: datasets/celeba-1024-lafin/train/images.flist
TRAIN_INPAINT_LANDMARK_FLIST: datasets/celeba-1024-lafin/train/landmarks.flist
TRAIN_LANDMARK_IMAGE_FLIST: null
TRAIN_LANDMARK_LANDMARK_FLIST: null
TRAIN_MASK_FLIST: datasets/celeba-1024-lafin/train/masks.flist
TV_LOSS_WEIGHT: 0.1
VAL_INPAINT_IMAGE_FLIST: datasets/celeba-1024-lafin/val/images.flist
VAL_INPAINT_LANDMARK_FLIST: datasets/celeba-1024-lafin/val/landmarks.flist
VAL_MASK_FLIST: datasets/celeba-1024-lafin/val/masks.flist

INPAINTOR: s2_ae_landmark_and_arcfaceis_in
NETWORK_CAPACITY: 64
NUM_LAYERS: 4
LATENT: 512
DATA_ROOT: 
DISTRIBUTED: False
LOCAL: True

