AUGMENTATION_TRAIN: 0
BATCH_SIZE: 4
BETA1: 0.0
BETA2: 0.9
CONTENT_LOSS_WEIGHT: 0.1
D2G_LR: 0.1
DATA_root: None
EVAL_INTERVAL: 0
GAN_LOSS: lsgan
GAN_POOL_SIZE: 0
GPU: [1]
INPAINT_ADV_LOSS_WEIGHT: 0.01
INPUT_SIZE: 256
L1_LOSS_WEIGHT: 1
LANDMARK_POINTS: 68
LOG_INTERVAL: 100
LR: 0.0001
MASK: 6
MAX_ITERS: 1300000
MODE: 2
MODEL: 3
SAMPLE_INTERVAL: 100
SAMPLE_SIZE: 2
SAVE_INTERVAL: 100
SEED: 10
STYLE_LOSS_WEIGHT: 250



TEST_INPAINT_IMAGE_FLIST: datasets/FFHQr/test/images.flist
TEST_INPAINT_LANDMARK_FLIST: datasets/FFHQr/test/landmarks.flist
TEST_LANDMARK_IMAGE_FLIST: null
TEST_LANDMARK_LANDMARK_FLIST: null
TEST_MASK_FLIST: datasets/FFHQr/test/masks.flist

# TEST_INPAINT_IMAGE_FLIST: datasets/Obama_face/test/images.flist
# TEST_INPAINT_LANDMARK_FLIST: datasets/Obama_face/test/landmarks.flist
# TEST_LANDMARK_IMAGE_FLIST: null
# TEST_LANDMARK_LANDMARK_FLIST: null
# TEST_MASK_FLIST: datasets/Obama_face/test/masks.flist

# TEST_INPAINT_IMAGE_FLIST: /data/chengbin/dataset/Obama100_1_big_lafin/images.flist
# TEST_INPAINT_LANDMARK_FLIST: /data/chengbin/dataset/Obama100_1_big_lafin/landmarks.flist
# TEST_LANDMARK_IMAGE_FLIST: null
# TEST_LANDMARK_LANDMARK_FLIST: null
# TEST_MASK_FLIST: /data/chengbin/dataset/Obama100_1_big_lafin/masks.flist

TRAIN_INPAINT_IMAGE_FLIST: datasets/FFHQr/train/images.flist
TRAIN_INPAINT_LANDMARK_FLIST: datasets/FFHQr/train/landmarks.flist
TRAIN_LANDMARK_IMAGE_FLIST: null
TRAIN_LANDMARK_LANDMARK_FLIST: null
TRAIN_MASK_FLIST: datasets/FFHQr/train/masks.flist
TV_LOSS_WEIGHT: 0.1
VAL_INPAINT_IMAGE_FLIST: datasets/FFHQr/val/images.flist
VAL_INPAINT_LANDMARK_FLIST: datasets/FFHQr/val/landmarks.flist
VAL_MASK_FLIST: datasets/FFHQr/val/masks.flist

DATA_ROOT: /opt/mnt/cb/dataset/FFHQ/ffhq-lafin
INPAINTOR: Inpainting_for_face_swap
NETWORK_CAPACITY: 64
NUM_LAYERS: 4
LATENT: 512
LOCAL: False
DISCRIMINATOR: lafin
