AUGMENTATION_TRAIN: 0
BATCH_SIZE: 2
BETA1: 0.0
BETA2: 0.9
CONTENT_LOSS_WEIGHT: 0.05
D2G_LR: 1
EVAL_INTERVAL: 0
GAN_LOSS: lsgan
GAN_POOL_SIZE: 0
GPU: [4,5]
INPAINT_ADV_LOSS_WEIGHT: 0.5
INPUT_SIZE: 512
L1_LOSS_WEIGHT: 4
LANDMARK_POINTS: 68
LOG_INTERVAL: 100
LR: 0.0001
MASK: 6
MAX_ITERS: 1300000
MODE: 2
MODEL: 3
SAMPLE_INTERVAL: 200
SAMPLE_SIZE: 2
SAVE_INTERVAL: 1000
SEED: 10
STYLE_LOSS_WEIGHT: 100
TEST_INPAINT_IMAGE_FLIST: datasets/ffhq/test/images.flist
TEST_INPAINT_LANDMARK_FLIST: datasets/ffhq/test/landmarks.flist
TEST_LANDMARK_IMAGE_FLIST: null
TEST_LANDMARK_LANDMARK_FLIST: null
TEST_MASK_FLIST: datasets/ffhq/test/masks.flist
TRAIN_INPAINT_IMAGE_FLIST: datasets/ffhq/train/images.flist
TRAIN_INPAINT_LANDMARK_FLIST: datasets/ffhq/train/landmarks.flist
TRAIN_LANDMARK_IMAGE_FLIST: null
TRAIN_LANDMARK_LANDMARK_FLIST: null
TRAIN_MASK_FLIST: datasets/ffhq/train/masks.flist
TV_LOSS_WEIGHT: 0.1
VAL_INPAINT_IMAGE_FLIST: datasets/ffhq/val/images.flist
VAL_INPAINT_LANDMARK_FLIST: datasets/ffhq/val/landmarks.flist
VAL_MASK_FLIST: datasets/ffhq/val/masks.flist

INPAINTOR: Inpainting_for_face_swap
NETWORK_CAPACITY: 64
NUM_LAYERS: 6
LATENT: 512
DATA_ROOT: /data/chengbin/ffhq-dataset/ffhq-lafin/
ARC_EVAL: True
LOSS_TYPE: inpainting

LM_LOSS_WEIGHT: 1
ID_LOSS_WEIGHT: 0.1

